### ISSUE TITLE
Fix failing blinded utxos

### ISSUE THREAD

**Issue by josediegorobles** [bitmask-stack/bitmask-core#10]
The process is working until the "Accept" part, and then in the server gives the problem that the blinding of the utxo it's not correct, but if you make the process entirely between web services is working ok, so something about the savidng of the utxo data has to be working bad.

- [ ] Make the full process: issue a token in your wallet, transfer to another wallet and accept.
- [ ] Verify if the problem is in the utxos-blinding saved on the memory or in the data sent to the accept web service
- [ ] Correct the problem

**Comment by cryptoquick** [comment]
I broke the token transfer stuff out into a separate issue #15, since that's a different problem than the blinded utxos.
