### ISSUE TITLE
Substituting Tupla for a struct

### ISSUE THREAD

**Issue by josediegorobles** [bitmask-stack/bitmask-core#117]
For more clarity of the code.

It's here:

In lib.rs this method:

`#[cfg(not(target_arch = "wasm32"))]`
`pub async fn transfer_assets(`
    `rgb_assets_descriptor_xpub: &str, // TODO: Privacy concerns. Not great, not terrible`
    `blinded_utxo: &str,`
    `amount: u64,`
    `asset_contract: &str,`
    `asset_utxos: Vec<LocalUtxo>,`
`) -> Result<(`
    `String, // bech32m compressed sten consignment`
    `String, // base64 bitcoin encoded psbt`
    `String, // json`
    `String,`
   `String,`
    `String,
`)> `

Must return a TransferAssetsResponse

**Comment by cryptoquick** [comment]
Closed by #124
