### ISSUE TITLE
Some issues with the send flow

### ISSUE THREAD

**Issue by DanGould** [bitmask-stack/bitmask-core#159]
- History shows strange send amounts. I'm not sure why, since BDK should be able to identify which address is change in simple spends
- "Transaction submitted successfully" provides no txid. On one occasion I saw this screen but my counterparty received no transaction. Without a txid I could not track it down

**Comment by cryptoquick** [comment]
These are both known issues, but we definitely need to track them. Thank you for reminding us :)

**Comment by cryptoquick** [comment]
The first issue is being tracked in #264, the second should be resolved now on beta.bitmask.app. Thanks for reporting this!
