### ISSUE TITLE
Hex and base64 codec methods

### ISSUE THREAD

**Issue by cryptoquick** [bitmask-stack/bitmask-core#189]
In carbonado.rs:
- [ ] `encode_base64(bytes: &[u8]) -> String`
- [ ] `encode_hex(bytes: &[u8]) -> String`
- [ ] `decode_base64(string: &str) -> Vec<u8>`
- [ ] `decode_hex(string: &str) -> Vec<u8>`

Don't forget to export these methods in web::carbonado.

**Comment by oacdutra** [comment]
@cryptoquick, for some reason, not close this issue after your merge. Can I close?
