### ISSUE TITLE
Track releases of dependencies

### ISSUE THREAD

**Issue by oacdutra** [bitmask-stack/bitmask-core#204]
The purpose of the issue is to map the changes made to the LNPBP projects, so that we can create PR for official releases.

**Descriptor-Wallet (BP-WG)**
- [x] Bump to Rust Amplify 4.x (wasm32)
- [x] Bump to Strict-Type 1.5.x (wasm32)
- [x] ~Support to spent output with tweak~
- [x] ~Support to change terminal derivation (not only index change)~

**BP-Foundation (BP-WG)**
- [x] Bump to Rust Amplify 4.x (wasm32)
- [x] Bump to Strict-Type 1.5.x (wasm32)

**RGB-Wallet (RGB-WG)**
- [x] STL Types API Improvements
- [x] Velocity Check Alternative
- [x] Expose DataAllocation
- [x] Allow Data State Transitions
- [x] Blank transitions with different ifaces

**RGB-Contracts (RGB-WG)**
- [x] Decoupling Electrum Client
- [x] Expose all Resolvers
- [x] Expose RGBDesc
- [x] Fix Taproot Merkle Tree
- [x] ~Add armored in Genesis~

**Comment by cryptoquick** [comment]
@josediegorobles This is still a 0.6.3 milestone task. It's the last one we need to close 0.6.3, and it's not yet finished.

**Comment by josediegorobles** [comment]
> @josediegorobles This is still a 0.6.3 milestone task. It's the last one we need to close 0.6.3, and it's not yet finished.

Ok perfect, I think I was a bit too much rushing
