### ISSUE TITLE
Nostr NIP 05 support

### ISSUE THREAD

**Issue by grunch** [bitmask-stack/bitmask-core#227]
NIP 05 allows to link a nostr pubkey with a internet domain in a `email like` way, making easier share our nostr identity, e.g., `negrunch@grunch.dev` redirects to  `npub1qqqqqqqx2tj99mng5qgc07cgezv5jm95dj636x4qsq7svwkwmwnse3rfkq`.

We can allow our users to have NIP 05 like `alice@bitmask.app` without much word, the backend work is already done on lndhubx, I will explain here how it works on lndhubx and what we need to implement it.

I know that bitmask wallet creates new nostr keys to new users, we can use that pubkey by default but we need to allow to the user to change it to some other pubkey they have, so the first thing to do is, after the new nostr key pair are created we should let know to lndhubx that user is linked to that pubkey hitting to this endpoint  `https://lndhubx-prod.bitmask.app/nostr_pubkey`

Here a curl example
```bash
$ curl --location 'https://lndhubx-prod.bitmask.app/nostr_pubkey' \
--header 'Content-Type: application/json' \
--header 'authorization: eyJ0eXAiOi...........OAR8dskUdf37TiJ_WTg' \
--data '{
    "pubkey": "000000000652e452ee68a01187fb08c899496cb46cb51d1aa0803d063acedba7"
}'
```
If the user wants to change the pubkey we should add a new input on settings for the user to change the pubkey

```bash
curl --location 'https://lndhubx-prod.bitmask.app/update_nostr_pubkey' \
--header 'Content-Type: application/json' \
--header 'authorization: eyJ0eXAiOiJKV....f37TiJ_WTg' \
--data '{
    "pubkey": "00027f5dc261875bb0cb4dc1c4bd130a43e4d8000a3af29d01c764163fd23e9d"
}'
```
![image](https://github.com/diba-io/bitmask-core/assets/228364/d64651c8-cc93-49ff-98fb-0b4658dc8c76)

After this we can use the NIP 05 right now, but in not a desirable way because lndhubx is linked to the domain `lndhubx-prod.bitmask.app` and it would be cool for users to have `alice@bitmask.app` instead of `alice@lndhubx-prod.bitmask.app`.

Here my nostr profile using NIP 05 as we can do it now
![image](https://github.com/diba-io/bitmask-core/assets/228364/60e61aea-8934-46d1-84d2-7bb806cfa7dd)

### Username

When a user creates a new wallet it is created a new lndhubx account for that user with a username like this `06405526ae42e9467bf3b436b8093fc96758c263` and the user is linked to that username forever, so after add the nostr pubkey this same user will have NIP05 like this 06405526ae42e9467bf3b436b8093fc96758c263@lndhubx-prod.bitmask.app` which is far from `alice@bitmask.app`.

To solve this I think we can do two things, one is to ask for a username on the wallet creation, the second is not that simple, I have to ask to lndhubx if allowing to the user to change the username is something feasible and then work on a PR.

If I have to choose I'll go with the first one.

### Domain

Change in the DNS the lndhubx from lndhubx-prod.bitmask.app to bitmask.app, that way when nostr clients ask to `https://bitmask.app/.well-known/nostr.json?name=negrunch` users are validated correctly.

Inmediate task to do:
- [x] #228

**Comment by cryptoquick** [comment]
This is done as of 0.6.2!
