### ISSUE TITLE
Duplicate words in mnemonic seed on wallet creation 

### ISSUE THREAD

**Issue by trevor-ofarrell** [bitmask-stack/bitmask-core#240]
<img width="1728" alt="Screen Shot 2023-05-20 at 3 40 00 AM" src="https://github.com/diba-io/bitmask-core/assets/47125174/988ed794-fdab-4cc7-bcb3-150f3a187cf8">

**Comment by cryptoquick** [comment]
Yeah, investigating it further, there's been a pretty serious oversight. I'm working on it now. I think we should switch to 24 words, btw, non-optional. We need to be seen as a wallet that takes security seriously.
