### ISSUE TITLE
Testnet coins can be sent to mainnet addresses

### ISSUE THREAD

**Issue by cryptoquick** [bitmask-stack/bitmask-core#260]
Apparently no checks are done at all if testnet coins are sent to a mainnet address. I'm a little worried it works in the other direction, too. Let's definitely make sure we check the HRP.

**Comment by oacdutra** [comment]
> Apparently no checks are done at all if testnet coins are sent to a mainnet address. I'm a little worried it works in the other direction, too. Let's definitely make sure we check the HRP.

Well, 

We can achievement that with improving type checks and custom errors check, right?

I intent make that after "stable version" of the RGB.

**Comment by cryptoquick** [comment]
I originally meant this in the context of bitcoin transfers, but we should also be careful to do this check in LN and RGB invoices.
