### ISSUE TITLE
Adding taproot support

### ISSUE THREAD

**Issue by josediegorobles** [bitmask-stack/bitmask-core#28]

**Comment by josediegorobles** [comment]
For now i've started an experimental branch: https://github.com/diba-io/bitmask-core/tree/feature/taproot and a draft PR: https://github.com/diba-io/bitmask-core/pull/29
Based on last RC for rust-bitcoin and the experimental branch for taproot https://github.com/diba-io/bitmask-core/tree/feature/taproot

**Comment by josediegorobles** [comment]
First we need to update to bdk 0.19

**Comment by cryptoquick** [comment]
We now have full P2TR support merged into the `development` branch.
