### ISSUE TITLE
Fund Vault Privacy

### ISSUE THREAD

**Issue by cryptoquick** [bitmask-stack/bitmask-core#291]
Randomly vary dust amounts within a certain range, and send to four different addresses instead of reusing each UDA and fungible address twice.

Example fund vault tx:
https://mempool.space/tx/c9e629f6f372a82e5bc0f49f8e4b861d6354a27a2996b787137f067350d079bb

**Comment by cryptoquick** [comment]
I would love to integrate fund_vault with payjoin @DanGould, for further privacy

**Comment by DanGould** [comment]
Is this an internal transaction between 2 accounts inside bitmask? Where can I read more about Fund Vault?

**Comment by cryptoquick** [comment]
It is, it's currently used to make four dust UTXOs for use with RGB:
https://github.com/diba-io/bitmask-core/blob/4e2d8315207c021671235cfaab8fc8dc2f31a14f/src/bitcoin.rs#L285-L342

We then need to replenish a dust UTXO from the user's bitcoin wallet with each transfer, and we want to maintain their privacy. Payjoin could really help with that, I think.
