### ISSUE TITLE
Persistence for all the asset data in the wallet

### ISSUE THREAD

**Issue by josediegorobles** [bitmask-stack/bitmask-core#30]
Getting all the data that we are receiving from the rgb-node and save it: genesis, consignments, disclosures, so we can auth in another node.
After that we need the extension part: https://github.com/diba-io/bitmask-extension/issues/101

**Comment by cryptoquick** [comment]
This work is pending Carbonado support now

**Comment by cryptoquick** [comment]
We'll probably store them in plaintext at first if I can't easily debug WASM Carbonado encryption.
I've outlined a schema and approach for this issue here:
https://github.com/diba-io/bitmask-core/issues/88

**Comment by oacdutra** [comment]
Can we close this issue?

**Comment by josediegorobles** [comment]
Yeah. With rgb 0.10 we are solving all this
