### ISSUE TITLE
RGB Transfer Batching

### ISSUE THREAD

**Issue by cryptoquick** [bitmask-stack/bitmask-core#304]
When a transfer is initiated, sync that specific RGB wallet, and check to see if there's already an RGB transfer operation in progress (unmined), and RBF with a new transfer that consolidates tokens onto the same change UTXO. If it's from the same UTXO, this should be done anyway, but if it's from a different UTXO, it can still save on fees. Combine with Payjoin for best results. If the RBF cannot be performed due to a block being mined at the same time, the transfer is adjusted accordingly.

**Comment by josediegorobles** [comment]
This is going to be very useful for the marketplace, we are ready to put it in a nearer milestone?

**Comment by josediegorobles** [comment]
This is going to be very useful for the marketplace, we are ready to put it in a nearer milestone @cryptoquick @crisdut ?

**Comment by cryptoquick** [comment]
I'm not sure about that, the 0.7 milestone already has quite a few issues in it, and this is just more of a scaling and user quality of life feature. I think we should keep it on 0.8 for now.

**Comment by josediegorobles** [comment]
Yeah, thinking better I think is not necessary for short term

**Comment by cryptoquick** [comment]
I've changed my mind, you're right, we definitely need this for the 0.7 release.

**Comment by lastdof** [comment]
I can't wait for this one . Did some assets with the beta and after being able to send some 3 to 4000 pepe, I get this error all the time : insufficient funds ( expected : XX / actual : more than XXX) . 
Also before, had to wait for 4 days a blocking tx with a very low sat/vb ( not rbf indeed) 
Thx

**Comment by cryptoquick** [comment]
It's definitely the second highest on our priority list, after #292
