### ISSUE TITLE
Use RGBA Base85 encoding for RGB strings

### ISSUE THREAD

**Issue by cryptoquick** [bitmask-stack/bitmask-core#320]
For long RGB strings returned by RGB methods such as consignments, contracts, and genesis, we should instead use ASCII-armored base85 encoding, as per Maxim's recommendation, like so:
https://github.com/RGB-WG/rgb-schemata/blob/master/schemata/CollectibleFungibleAssets-RGB25.rgba

**Comment by oacdutra** [comment]
I think we use that in majority operations, but I intent write some tests to cover the format in import and transfer operations, ok?

If works, I will close this PR.

**Comment by cryptoquick** [comment]
It seems to work, we just didn't have the armored property in one of the TypeScript interfaces. Thanks!
