### ISSUE TITLE
Hide Asset

### ISSUE THREAD

**Issue by cryptoquick** [bitmask-stack/bitmask-core#343]
We need a method accessible from web.rs to hide RGB assets in the stash.

Subsequently, ContractResponse should then have a property, is_hidden: bool.

**Comment by josediegorobles** [comment]
It's this https://github.com/diba-io/bitmask-core/issues/324, isn't it? But making sure is accessible from web.rs

**Comment by josediegorobles** [comment]
Yeah it's the same
