### ISSUE TITLE
Automatic verify of all transactions

### ISSUE THREAD

**Issue by josediegorobles** [bitmask-stack/bitmask-core#344]
Now we are using verify_transfers for verify and accept transfers but I think that easier and more transparent to the users is:

- [ ] Internal method (not endpoint) to verify ALL pending transactions of all users
- [ ] Cron Job for execute it every 5 minutes (or every time a block is mined) in the server
- [ ] An endpoint for know if a user have pending transactions, with nostr key as parameter and returns true or false for every iface.

**Comment by oacdutra** [comment]
Hi @josediegorobles, 

I'm marking with wontfix, according to our previous alignment, ok?
