### ISSUE TITLE
Keep track of the lost sats

### ISSUE THREAD

**Issue by josediegorobles** [bitmask-stack/bitmask-core#37]
In send_tokens we are sending to our own address 546 sats but the public key is being tweak and the wallet don't know that exists. So we are burning a bit of sats as a second "fee". We have to correct this and get the utxo in our wallet.

**Comment by oacdutra** [comment]
> In send_tokens we are sending to our own address 546 sats but the public key is being tweak and the wallet don't know that exists. So we are burning a bit of sats as a second "fee". We have to correct this and get the utxo in our wallet.

Hi @josediegorobles, I think with this new version of the RGB, this can be mitigate. Now we spent output with tapret commitments.

I will make a smoke tests relation that and if everything works, I will close this PR, ok?

**Comment by josediegorobles** [comment]
Of course, go ahead
