### ISSUE TITLE
Support baid58 encoding for ids

### ISSUE THREAD

**Issue by cryptoquick** [bitmask-stack/bitmask-core#387]
See: https://spec.rgb.tech/application-level/identifiers

**Comment by oacdutra** [comment]
> See: https://spec.rgb.tech/application-level/identifiers

I dont understand this.

Today we use base58 for consig_ids, contracts_ids, offers, bids, etc..

**Comment by cryptoquick** [comment]
Compare the identifiers we generate with the identifiers in the document. The formatting differs.

**Comment by cryptoquick** [comment]
Looks like our IDs now look like this:
`rgb:4bZiD35-SSLFGgujj-3jwgavEcz-GHioQ1yjt-373jDsgem-jAHJBY`
We should be good on this issue.
