### ISSUE TITLE
Taproot support

### ISSUE THREAD

**Issue by cryptoquick** [bitmask-stack/bitmask-core#4]
Add taproot address support (bc1p)

**Comment by cryptoquick** [comment]
Looks like this is blocked by: https://github.com/bitcoindevkit/bdk/issues/63

**Comment by josediegorobles** [comment]
Yeah, i was paying attention to that, but it's good to have the issue open. I'm going to assign you and as soon as bdk have full taproot support you can start

**Comment by cryptoquick** [comment]
I don't think BDK had Taproot support yet. It doesn't generate bc1p addresses afaik. They seem to imply they might require a new feature in BDK for multiple wallets, and they'd have to implement the feature for moving funds from P2TR to P2WPKH addresses and vice versa.

**Comment by josediegorobles** [comment]
Yeah, I think I didn't express myself well, they are starting the work now.
