### ISSUE TITLE
BitMask local node

### ISSUE THREAD

**Issue by cryptoquick** [bitmask-stack/bitmask-core#78]
In case people don't want to use our lambdas, they can run their own local node instead

**Comment by josediegorobles** [comment]
Ofc, we wanted this from the start

**Comment by cryptoquick** [comment]
I think I'm gonna work on this so we can do local testing of BitMask methods directly with the extension .env instead of needing to develop using the lambdas. Lambdas should just be for prod. Then if users want, they can run their own stack too, so it kills two birds with one stone, it makes development faster and also helps give our users self-sovereignty :)
