### ISSUE TITLE
Create a new change UTXO in the same tx as an asset transfer

### ISSUE THREAD

**Issue by cryptoquick** [bitmask-stack/bitmask-core#81]
This way there'll always be a new change UTXO available for RGB assets.

AC: Asset test passes repeatably on a wallet with lots of sats

**Comment by cryptoquick** [comment]
And also, this keeps us from essentially "burning" our sats by spending them to an OP_RETURN with no change output; the balance is moved to the next output, minus the fees.

Eventually the tx output will dip below the unspendable limit if more sats aren't added to the vault, so perhaps we should also have a way to pull some sats in from the full wallet to fund the vault automatically. I'm not sure if we should do this 10k sats at a time or if that should be configurable, but the fee economy for this approach should be better than using an input from the full wallet to pay for fees for each transfer, because the funds for the entire output would otherwise become unspendable or rejected for being under the fee limit.

**Comment by josediegorobles** [comment]
I think that bitmask-core must maintain the sats configurable but maybe in bitmask-extension to have a default reasonable number of sats so it's easier for the user (and maybe put it configurable in settings, but not every time we need a fund)

**Comment by josediegorobles** [comment]
But yeah, I'm ok with all you are saying here and is more or less what I thought from the start

**Comment by cryptoquick** [comment]
Haha, I'm glad what I'm thinking makes sense, and yeah, having a configurable default to "top up" your vault with sats is probably best. It might take some explanation to our users, "a separate wallet is used for your tokens, and we call that a vault. it uses the same seed as your sats wallet, but it has a different balance and will periodically need to be topped up for fees."

**Comment by josediegorobles** [comment]
We can start with that text yeah. Default action and parameters but explaining to users and letting config at settings. I think it's the better for usability.

**Comment by grunch** [comment]
I think I understand this issue but I'll try to make an example and please let me know if I am right or wrong.


Alice created a new asset, when Alice created the tokens those were asigned to UTXO `aa..bb:0`, the vault have now 21M coins, the UTXO containing the tokens (the vault) should have always at least 10000 sats.

Alice have a wallet with 3 UTXOs:

```
1. {
	"sats_amount": 10000,
	"asset_amount": 21000000,
	"outpoint": "aa..bb:0",
}

2. {
	"sats_amount": 5000,
	"outpoint": "aa..cc:1",
}

3. {
	"sats_amount": 10000,
	"outpoint": "aa..dd:1",
}
```


Everytime Alice send tokens we need to move all change tokens to a new UTXO with 10000 sats or more.
 
Alice wants to send 1000 tokens to Bob, when she send the tokens the wallet use UTXO `aa..bb:0`, this UTXO only have 10000 sats, we will need to use another UTXO to pay the mining fee and have more than 10000 to be allowed to spend tokens in the future.

In this case the mining fee will be 200 sats, so the wallet uses UTXO 1 and 2 and send 10000 + 5000 - 200 = 14800 sats to a new change UTXO `aa..ee:0`, in the same operation the wallet send 1000 tokens to bob rgb address and send 20999000 tokens to the same change UTXO `aa..ee:0`.

These are the final UTXOs from Alice:
```

1. {
	"sats_amount": 10000,
	"outpoint": "aa..dd:1",
}

2. {
	"sats_amount": 14800,
	"asset_amount": 20999000,
	"outpoint": "aa..ee:0",
}
```

**Comment by cryptoquick** [comment]
This work would essentially be replaced by #191
